#include "gxm_types.h"
#include <stdio.h>

#define CASE2STR(val) \
  case val: return #val;

static char buffer[64];

const char *textureBaseFormat2str(SceGxmTextureFormat format) {
  switch(format & 0xff000000) {
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U8U3U3U2);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U5U6U5);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S5S5U6);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U8U8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S8S8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_F16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U16U16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S16S16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_F16F16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_F32);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_F32M);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_X8S8S8U8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_X8U24);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U32);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S32);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_SE5M9M9M9);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_F11F11F10);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_F32F32);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U32U32);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_PVRT2BPP);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_PVRT4BPP);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_PVRTII2BPP);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_PVRTII4BPP);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_UBC1);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_UBC2);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_UBC3);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_YUV420P2);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_YUV420P3);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_YUV422);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_P4);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_P8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U8U8U8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_S8S8S8);
    CASE2STR(SCE_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10);
    default: break;
  }

  return "unknown base format";
}

const char *textureSwizzle4Mode2str(SceGxmTextureFormat format) {
  switch (format & 0x0000f000) {
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE4_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE4_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE4_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE4_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE4_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE4_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE4_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE4_BGR1);
    default: break;
  }
  
  return "unknown swizzle 4 mode";
}

const char *textureSwizzle3Mode2str(SceGxmTextureFormat format) {
  switch (format & 0x0000f000) {
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE3_BGR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE3_RGB);
    default: break;
  }
  return "unknown swizzle 3 mode";
}

const char *textureSwizzle2Mode2str(SceGxmTextureFormat format) {
  switch (format & 0x0000f000) {
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE2_GR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE2_00GR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE2_GRRR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE2_RGGG);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE2_GRGR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE2_00RG);
    default: break;
  }
  return "unknown swizzle 2 mode";
}

const char *textureSwizzle2AltMode2str(SceGxmTextureFormat format) {
  switch (format & 0x0000f000) {
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE2_SD);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE2_DS);
    default: break;
  }
  return "unknown swizzle 2 alt mode";
}

const char *textureSwizzle1Mode2str(SceGxmTextureFormat format) {
  switch (format & 0x0000f000) {
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE1_R);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE1_000R);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE1_111R);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE1_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE1_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE1_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE1_R000);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE1_R111);
    default: break;
  }

  return "unknown swizzle 1 mode";
}

const char *textureSwizzleYUV422Mode2str(SceGxmTextureFormat format) {
  switch (format & 0x0000f000) {
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_YUYV_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_YVYU_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_UYVY_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_VYUY_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_YUYV_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_YVYU_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_UYVY_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_VYUY_CSC1);
    default: break;
  }

  return "unknown swizzle YUV422 mode";
}

const char *textureSwizzleYUV420Mode2str(SceGxmTextureFormat format) {
  switch (format & 0x0000f000) {
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_YUV_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_YVU_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_YUV_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_SWIZZLE_YVU_CSC1);
    default: break;
  }

  return "unknown swizzle YUV420 mode";
}

const char *textureSwizzleMode2str(SceGxmTextureFormat format) {
  switch (format & 0xff00f000) {
  case SCE_GXM_TEXTURE_FORMAT_U8_000R:
  case SCE_GXM_TEXTURE_FORMAT_U8_111R:
  case SCE_GXM_TEXTURE_FORMAT_U8_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_U8_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_U8_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_U8_R000:
  case SCE_GXM_TEXTURE_FORMAT_U8_R111:
  case SCE_GXM_TEXTURE_FORMAT_U8_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_S8_000R:
  case SCE_GXM_TEXTURE_FORMAT_S8_111R:
  case SCE_GXM_TEXTURE_FORMAT_S8_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_S8_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_S8_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_S8_R000:
  case SCE_GXM_TEXTURE_FORMAT_S8_R111:
  case SCE_GXM_TEXTURE_FORMAT_S8_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U4U4U4U4_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_U4U4U4U4_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_U4U4U4U4_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_U4U4U4U4_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X4U4U4U4_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X4U4U4U4_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_U4U4U4X4_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_U4U4U4X4_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U8U3U3U2_ARGB:
    break;

  case SCE_GXM_TEXTURE_FORMAT_U1U5U5U5_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_U1U5U5U5_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_U5U5U5U1_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_U5U5U5U1_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X1U5U5U5_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X1U5U5U5_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_U5U5U5X1_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_U5U5U5X1_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U5U6U5_BGR:
  case SCE_GXM_TEXTURE_FORMAT_U5U6U5_RGB:
    return textureSwizzle3Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U6S5S5_BGR:
  case SCE_GXM_TEXTURE_FORMAT_S5S5U6_RGB:
    return textureSwizzle3Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U8U8_00GR:
  case SCE_GXM_TEXTURE_FORMAT_U8U8_GRRR:
  case SCE_GXM_TEXTURE_FORMAT_U8U8_RGGG:
  case SCE_GXM_TEXTURE_FORMAT_U8U8_GRGR:
  case SCE_GXM_TEXTURE_FORMAT_U8U8_00RG:
  case SCE_GXM_TEXTURE_FORMAT_U8U8_GR:
    return textureSwizzle2Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_S8S8_00GR:
  case SCE_GXM_TEXTURE_FORMAT_S8S8_GRRR:
  case SCE_GXM_TEXTURE_FORMAT_S8S8_RGGG:
  case SCE_GXM_TEXTURE_FORMAT_S8S8_GRGR:
  case SCE_GXM_TEXTURE_FORMAT_S8S8_00RG:
  case SCE_GXM_TEXTURE_FORMAT_S8S8_GR:
    return textureSwizzle2Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U16_000R:
  case SCE_GXM_TEXTURE_FORMAT_U16_111R:
  case SCE_GXM_TEXTURE_FORMAT_U16_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_U16_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_U16_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_U16_R000:
  case SCE_GXM_TEXTURE_FORMAT_U16_R111:
  case SCE_GXM_TEXTURE_FORMAT_U16_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_S16_000R:
  case SCE_GXM_TEXTURE_FORMAT_S16_111R:
  case SCE_GXM_TEXTURE_FORMAT_S16_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_S16_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_S16_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_S16_R000:
  case SCE_GXM_TEXTURE_FORMAT_S16_R111:
  case SCE_GXM_TEXTURE_FORMAT_S16_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_F16_000R:
  case SCE_GXM_TEXTURE_FORMAT_F16_111R:
  case SCE_GXM_TEXTURE_FORMAT_F16_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_F16_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_F16_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_F16_R000:
  case SCE_GXM_TEXTURE_FORMAT_F16_R111:
  case SCE_GXM_TEXTURE_FORMAT_F16_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U8U8U8U8_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_U8U8U8U8_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_U8U8U8U8_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_U8U8U8U8_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X8U8U8U8_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X8U8U8U8_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_U8U8U8X8_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_U8U8U8X8_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_S8S8S8S8_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_S8S8S8S8_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_S8S8S8S8_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_S8S8S8S8_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X8S8S8S8_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X8S8S8S8_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_S8S8S8X8_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_S8S8S8X8_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U2U10U10U10_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_U2U10U10U10_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_U10U10U10U2_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_U10U10U10U2_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X2U10U10U10_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X2U10U10U10_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_U10U10U10X2_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_U10U10U10X2_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U16U16_00GR:
  case SCE_GXM_TEXTURE_FORMAT_U16U16_GRRR:
  case SCE_GXM_TEXTURE_FORMAT_U16U16_RGGG:
  case SCE_GXM_TEXTURE_FORMAT_U16U16_GRGR:
  case SCE_GXM_TEXTURE_FORMAT_U16U16_00RG:
  case SCE_GXM_TEXTURE_FORMAT_U16U16_GR:
    return textureSwizzle2Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_S16S16_00GR:
  case SCE_GXM_TEXTURE_FORMAT_S16S16_GRRR:
  case SCE_GXM_TEXTURE_FORMAT_S16S16_RGGG:
  case SCE_GXM_TEXTURE_FORMAT_S16S16_GRGR:
  case SCE_GXM_TEXTURE_FORMAT_S16S16_00RG:
  case SCE_GXM_TEXTURE_FORMAT_S16S16_GR:
    return textureSwizzle2Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_F16F16_00GR:
  case SCE_GXM_TEXTURE_FORMAT_F16F16_GRRR:
  case SCE_GXM_TEXTURE_FORMAT_F16F16_RGGG:
  case SCE_GXM_TEXTURE_FORMAT_F16F16_GRGR:
  case SCE_GXM_TEXTURE_FORMAT_F16F16_00RG:
  case SCE_GXM_TEXTURE_FORMAT_F16F16_GR:
    return textureSwizzle2Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_F32_000R:
  case SCE_GXM_TEXTURE_FORMAT_F32_111R:
  case SCE_GXM_TEXTURE_FORMAT_F32_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_F32_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_F32_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_F32_R000:
  case SCE_GXM_TEXTURE_FORMAT_F32_R111:
  case SCE_GXM_TEXTURE_FORMAT_F32_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_F32M_000R:
  case SCE_GXM_TEXTURE_FORMAT_F32M_111R:
  case SCE_GXM_TEXTURE_FORMAT_F32M_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_F32M_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_F32M_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_F32M_R000:
  case SCE_GXM_TEXTURE_FORMAT_F32M_R111:
  case SCE_GXM_TEXTURE_FORMAT_F32M_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_X8S8S8U8_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X8U8S8S8_1RGB:
    return textureSwizzle3Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_X8U24_SD:
  case SCE_GXM_TEXTURE_FORMAT_U24X8_DS:
    return textureSwizzle2AltMode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U32_000R:
  case SCE_GXM_TEXTURE_FORMAT_U32_111R:
  case SCE_GXM_TEXTURE_FORMAT_U32_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_U32_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_U32_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_U32_R000:
  case SCE_GXM_TEXTURE_FORMAT_U32_R111:
  case SCE_GXM_TEXTURE_FORMAT_U32_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_S32_000R:
  case SCE_GXM_TEXTURE_FORMAT_S32_111R:
  case SCE_GXM_TEXTURE_FORMAT_S32_RRRR:
  case SCE_GXM_TEXTURE_FORMAT_S32_0RRR:
  case SCE_GXM_TEXTURE_FORMAT_S32_1RRR:
  case SCE_GXM_TEXTURE_FORMAT_S32_R000:
  case SCE_GXM_TEXTURE_FORMAT_S32_R111:
  case SCE_GXM_TEXTURE_FORMAT_S32_R:
    return textureSwizzle1Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_SE5M9M9M9_BGR:
  case SCE_GXM_TEXTURE_FORMAT_SE5M9M9M9_RGB:
    return textureSwizzle3Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_F10F11F11_BGR:
  case SCE_GXM_TEXTURE_FORMAT_F11F11F10_RGB:
    return textureSwizzle3Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_F16F16F16F16_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_F16F16F16F16_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_F16F16F16F16_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_F16F16F16F16_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X16F16F16F16_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X16F16F16F16_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_F16F16F16X16_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_F16F16F16X16_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U16U16U16U16_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_U16U16U16U16_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_U16U16U16U16_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_U16U16U16U16_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X16U16U16U16_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X16U16U16U16_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_U16U16U16X16_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_U16U16U16X16_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_S16S16S16S16_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_S16S16S16S16_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_S16S16S16S16_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_S16S16S16S16_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X16S16S16S16_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X16S16S16S16_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_S16S16S16X16_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_S16S16S16X16_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_F32F32_00GR:
  case SCE_GXM_TEXTURE_FORMAT_F32F32_GRRR:
  case SCE_GXM_TEXTURE_FORMAT_F32F32_RGGG:
  case SCE_GXM_TEXTURE_FORMAT_F32F32_GRGR:
  case SCE_GXM_TEXTURE_FORMAT_F32F32_00RG:
  case SCE_GXM_TEXTURE_FORMAT_F32F32_GR:
    return textureSwizzle2Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U32U32_00GR:
  case SCE_GXM_TEXTURE_FORMAT_U32U32_GRRR:
  case SCE_GXM_TEXTURE_FORMAT_U32U32_RGGG:
  case SCE_GXM_TEXTURE_FORMAT_U32U32_GRGR:
  case SCE_GXM_TEXTURE_FORMAT_U32U32_00RG:
  case SCE_GXM_TEXTURE_FORMAT_U32U32_GR:
    return textureSwizzle2Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_PVRT2BPP_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_PVRT2BPP_1BGR:

  case SCE_GXM_TEXTURE_FORMAT_PVRT4BPP_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_PVRT4BPP_1BGR:

  case SCE_GXM_TEXTURE_FORMAT_PVRTII2BPP_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_PVRTII2BPP_1BGR:

  case SCE_GXM_TEXTURE_FORMAT_PVRTII4BPP_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_PVRTII4BPP_1BGR:

  case SCE_GXM_TEXTURE_FORMAT_UBC1_ABGR:

  case SCE_GXM_TEXTURE_FORMAT_UBC2_ABGR:

  case SCE_GXM_TEXTURE_FORMAT_UBC3_ABGR:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_YUV420P2_CSC0:
  case SCE_GXM_TEXTURE_FORMAT_YVU420P2_CSC0:
  case SCE_GXM_TEXTURE_FORMAT_YUV420P2_CSC1:
  case SCE_GXM_TEXTURE_FORMAT_YVU420P2_CSC1:

  case SCE_GXM_TEXTURE_FORMAT_YUV420P3_CSC0:
  case SCE_GXM_TEXTURE_FORMAT_YVU420P3_CSC0:
  case SCE_GXM_TEXTURE_FORMAT_YUV420P3_CSC1:
  case SCE_GXM_TEXTURE_FORMAT_YVU420P3_CSC1:
    return textureSwizzleYUV420Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_YUYV422_CSC0:
  case SCE_GXM_TEXTURE_FORMAT_YVYU422_CSC0:
  case SCE_GXM_TEXTURE_FORMAT_UYVY422_CSC0:
  case SCE_GXM_TEXTURE_FORMAT_VYUY422_CSC0:
  case SCE_GXM_TEXTURE_FORMAT_YUYV422_CSC1:
  case SCE_GXM_TEXTURE_FORMAT_YVYU422_CSC1:
  case SCE_GXM_TEXTURE_FORMAT_UYVY422_CSC1:
  case SCE_GXM_TEXTURE_FORMAT_VYUY422_CSC1:
    return textureSwizzleYUV422Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_P4_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_P4_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_P4_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_P4_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_P4_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_P4_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_P4_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_P4_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_P8_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_P8_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_P8_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_P8_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_P8_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_P8_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_P8_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_P8_BGR1:
    return textureSwizzle4Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U8U8U8_BGR:
  case SCE_GXM_TEXTURE_FORMAT_U8U8U8_RGB:

  case SCE_GXM_TEXTURE_FORMAT_S8S8S8_BGR:
  case SCE_GXM_TEXTURE_FORMAT_S8S8S8_RGB:
    return textureSwizzle3Mode2str(format);

  case SCE_GXM_TEXTURE_FORMAT_U2F10F10F10_ABGR:
  case SCE_GXM_TEXTURE_FORMAT_U2F10F10F10_ARGB:
  case SCE_GXM_TEXTURE_FORMAT_F10F10F10U2_RGBA:
  case SCE_GXM_TEXTURE_FORMAT_F10F10F10U2_BGRA:
  case SCE_GXM_TEXTURE_FORMAT_X2F10F10F10_1BGR:
  case SCE_GXM_TEXTURE_FORMAT_X2F10F10F10_1RGB:
  case SCE_GXM_TEXTURE_FORMAT_F10F10F10X2_RGB1:
  case SCE_GXM_TEXTURE_FORMAT_F10F10F10X2_BGR1:
    return textureSwizzle4Mode2str(format);
  default: break;
  }

  return "unknown swizzle mode";
}

const char *textureFormat2str(SceGxmTextureFormat format) {
  switch (format) {
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U4U4U4U4_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U4U4U4U4_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U4U4U4U4_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U4U4U4U4_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X4U4U4U4_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X4U4U4U4_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U4U4U4X4_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U4U4U4X4_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U3U3U2_ARGB);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U1U5U5U5_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U1U5U5U5_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U5U5U5U1_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U5U5U5U1_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X1U5U5U5_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X1U5U5U5_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U5U5U5X1_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U5U5U5X1_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U5U6U5_BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U5U6U5_RGB);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U6S5S5_BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S5S5U6_RGB);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8_00GR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8_GRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8_RGGG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8_GRGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8_00RG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8_GR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8_00GR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8_GRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8_RGGG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8_GRGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8_00RG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8_GR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8U8U8_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8U8U8_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8U8U8_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8U8U8_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X8U8U8U8_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X8U8U8U8_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8U8X8_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8U8X8_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8S8S8_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8S8S8_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8S8S8_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8S8S8_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X8S8S8S8_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X8S8S8S8_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8S8X8_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8S8X8_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U2U10U10U10_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U2U10U10U10_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U10U10U10U2_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U10U10U10U2_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X2U10U10U10_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X2U10U10U10_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U10U10U10X2_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U10U10U10X2_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16_00GR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16_GRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16_RGGG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16_GRGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16_00RG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16_GR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16_00GR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16_GRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16_RGGG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16_GRGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16_00RG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16_GR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16_00GR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16_GRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16_RGGG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16_GRGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16_00RG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16_GR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32M_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32M_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32M_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32M_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32M_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32M_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32M_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32M_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X8S8S8U8_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X8U8S8S8_1RGB);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X8U24_SD);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U24X8_DS);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S32_000R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S32_111R);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S32_RRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S32_0RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S32_1RRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S32_R000);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S32_R111);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S32_R);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_SE5M9M9M9_BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_SE5M9M9M9_RGB);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F10F11F11_BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F11F11F10_RGB);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16F16F16_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16F16F16_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16F16F16_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16F16F16_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X16F16F16F16_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X16F16F16F16_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16F16X16_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F16F16F16X16_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16U16U16_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16U16U16_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16U16U16_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16U16U16_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X16U16U16U16_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X16U16U16U16_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16U16X16_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U16U16U16X16_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16S16S16_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16S16S16_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16S16S16_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16S16S16_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X16S16S16S16_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X16S16S16S16_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16S16X16_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S16S16S16X16_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32F32_00GR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32F32_GRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32F32_RGGG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32F32_GRGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32F32_00RG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F32F32_GR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32U32_00GR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32U32_GRRR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32U32_RGGG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32U32_GRGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32U32_00RG);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U32U32_GR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRT2BPP_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRT2BPP_1BGR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRT4BPP_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRT4BPP_1BGR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRTII2BPP_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRTII2BPP_1BGR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRTII4BPP_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRTII4BPP_1BGR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_UBC1_ABGR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_UBC2_ABGR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_UBC3_ABGR);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YUV420P2_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YVU420P2_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YUV420P2_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YVU420P2_CSC1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YUV420P3_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YVU420P3_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YUV420P3_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YVU420P3_CSC1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YUYV422_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YVYU422_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_UYVY422_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_VYUY422_CSC0);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YUYV422_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_YVYU422_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_UYVY422_CSC1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_VYUY422_CSC1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P4_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P4_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P4_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P4_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P4_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P4_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P4_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P4_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P8_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P8_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P8_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P8_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P8_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P8_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P8_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_P8_BGR1);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8U8_BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U8U8U8_RGB);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8S8_BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_S8S8S8_RGB);

    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U2F10F10F10_ABGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_U2F10F10F10_ARGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F10F10F10U2_RGBA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F10F10F10U2_BGRA);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X2F10F10F10_1BGR);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_X2F10F10F10_1RGB);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F10F10F10X2_RGB1);
    CASE2STR(SCE_GXM_TEXTURE_FORMAT_F10F10F10X2_BGR1);

    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_L8);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_A8);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_R8);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_A4R4G4B4);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_A1R5G5B5);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_R5G6B5);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_A8L8);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_L8A8);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_G8R8);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_L16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_A16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_R16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_D16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_LF16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_AF16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_RF16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_A8R8G8B8);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_A8B8G8R8);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_AF16LF16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_LF16AF16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_GF16RF16);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_LF32M);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_AF32M);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_RF32M);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_DF32M);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_VYUY);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_YVYU);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_UBC1);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_UBC2);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_UBC3);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRT2BPP);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRT4BPP);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRTII2BPP);
    //CASE2STR(SCE_GXM_TEXTURE_FORMAT_PVRTII4BPP);
    default: {
      snprintf(buffer, 64, "0x%X", (unsigned int)format);
      return buffer;
    }
  }
}

const char* attributeFormat2str(SceGxmAttributeFormat format) {
  switch(format) {
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_U8);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_S8);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_U16);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_S16);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_U8N);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_S8N);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_U16N);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_S16N);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_F16);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_F32);
  CASE2STR(SCE_GXM_ATTRIBUTE_FORMAT_UNTYPED);
  default: break;
  }

  return "unknown attribute format";
}

const char* parameterType2str(SceGxmParameterType type) {

  switch(type) {
  CASE2STR(SCE_GXM_PARAMETER_TYPE_F32);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_F16);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_C10);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_U32);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_S32);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_U16);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_S16);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_U8);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_S8);
  CASE2STR(SCE_GXM_PARAMETER_TYPE_AGGREGATE);
  default: break;
  }

  return "unknown parameter type";
}

const char* parameterSemantic2str(SceGxmParameterSemantic semantic) {

  switch(semantic) {
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_NONE);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_ATTR);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_BCOL);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_BINORMAL);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_BLENDINDICES);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_BLENDWEIGHT);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_COLOR);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_DIFFUSE);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_FOGCOORD);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_NORMAL);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_POINTSIZE);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_POSITION);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_SPECULAR);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_TANGENT);
  CASE2STR(SCE_GXM_PARAMETER_SEMANTIC_TEXCOORD);
  default: break;
  }

  return "unknown parameter semantice";
}
