/******************************************************************************
 * The MIT License (MIT)
 *
 * Copyright (c) 2019-2020 Baldur Karlsson
 * Copyright (c) 2014 Crytek
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 ******************************************************************************/

#pragma once

#include "common/common.h"
#include "core/core.h"
#include "maths/vec.h"

#include "official/gxm.h"

#define IMPLEMENT_FUNCTION_SERIALISED(ret, func, ...) \
  ret func(__VA_ARGS__);                              \
  template <typename SerialiserType>                  \
  bool CONCAT(Serialise_, func)(SerialiserType & ser, ##__VA_ARGS__);

#define INSTANTIATE_FUNCTION_SERIALISED(ret, func, ...)                                   \
  template bool WrappedGXM::CONCAT(Serialise_, func(ReadSerialiser &ser, ##__VA_ARGS__)); \
  template bool WrappedGXM::CONCAT(Serialise_, func(WriteSerialiser &ser, ##__VA_ARGS__));

enum class GXMChunk : uint32_t
{
  DeviceInitialisation = (uint32_t)SystemChunk::FirstDriverChunk,

  MakeContextCurrent,

  vrapi_CreateTextureSwapChain,
  vrapi_CreateTextureSwapChain2,

  sceGxmAddRazorGpuCaptureBuffer,
  sceGxmBeginCommandList,
  sceGxmBeginScene,
  sceGxmBeginSceneEx,
  sceGxmColorSurfaceGetClip,
  sceGxmColorSurfaceGetData,
  sceGxmColorSurfaceGetDitherMode,
  sceGxmColorSurfaceGetFormat,
  sceGxmColorSurfaceGetGammaMode,
  sceGxmColorSurfaceGetScaleMode,
  sceGxmColorSurfaceGetStrideInPixels,
  sceGxmColorSurfaceGetType,
  sceGxmColorSurfaceInit,
  sceGxmColorSurfaceInitDisabled,
  sceGxmColorSurfaceIsEnabled,
  sceGxmColorSurfaceSetClip,
  sceGxmColorSurfaceSetData,
  sceGxmColorSurfaceSetDitherMode,
  sceGxmColorSurfaceSetFormat,
  sceGxmColorSurfaceSetGammaMode,
  sceGxmColorSurfaceSetScaleMode,
  sceGxmCreateContext,
  sceGxmCreateDeferredContext,
  sceGxmCreateRenderTarget,
  sceGxmDepthStencilSurfaceGetBackgroundDepth,
  sceGxmDepthStencilSurfaceGetBackgroundMask,
  sceGxmDepthStencilSurfaceGetBackgroundStencil,
  sceGxmDepthStencilSurfaceGetForceLoadMode,
  sceGxmDepthStencilSurfaceGetForceStoreMode,
  sceGxmDepthStencilSurfaceGetFormat,
  sceGxmDepthStencilSurfaceGetStrideInSamples,
  sceGxmDepthStencilSurfaceInit,
  sceGxmDepthStencilSurfaceInitDisabled,
  sceGxmDepthStencilSurfaceIsEnabled,
  sceGxmDepthStencilSurfaceSetBackgroundDepth,
  sceGxmDepthStencilSurfaceSetBackgroundMask,
  sceGxmDepthStencilSurfaceSetBackgroundStencil,
  sceGxmDepthStencilSurfaceSetForceLoadMode,
  sceGxmDepthStencilSurfaceSetForceStoreMode,
  sceGxmDestroyContext,
  sceGxmDestroyDeferredContext,
  sceGxmDestroyRenderTarget,
  sceGxmDisplayQueueAddEntry,
  sceGxmDisplayQueueFinish,
  sceGxmDraw,
  sceGxmDrawInstanced,
  sceGxmDrawPrecomputed,
  sceGxmEndCommandList,
  sceGxmEndScene,
  sceGxmExecuteCommandList,
  sceGxmFinish,
  sceGxmFragmentProgramGetPassType,
  sceGxmFragmentProgramGetProgram,
  sceGxmFragmentProgramIsEnabled,
  sceGxmGetContextType,
  sceGxmGetDeferredContextFragmentBuffer,
  sceGxmGetDeferredContextVdmBuffer,
  sceGxmGetDeferredContextVertexBuffer,
  sceGxmGetNotificationRegion,
  sceGxmGetParameterBufferThreshold,
  sceGxmGetPrecomputedDrawSize,
  sceGxmGetPrecomputedFragmentStateSize,
  sceGxmGetPrecomputedVertexStateSize,
  sceGxmGetRenderTargetMemSize,
  sceGxmInitialize,
  sceGxmIsDebugVersion,
  sceGxmMapFragmentUsseMemory,
  sceGxmMapMemory,
  sceGxmMapVertexUsseMemory,
  sceGxmMidSceneFlush,
  sceGxmNotificationWait,
  sceGxmPadHeartbeat,
  sceGxmPadTriggerGpuPaTrace,
  sceGxmPopUserMarker,
  sceGxmPrecomputedDrawInit,
  sceGxmPrecomputedDrawSetAllVertexStreams,
  sceGxmPrecomputedDrawSetParams,
  sceGxmPrecomputedDrawSetParamsInstanced,
  sceGxmPrecomputedDrawSetVertexStream,
  sceGxmPrecomputedFragmentStateGetDefaultUniformBuffer,
  sceGxmPrecomputedFragmentStateInit,
  sceGxmPrecomputedFragmentStateSetAllAuxiliarySurfaces,
  sceGxmPrecomputedFragmentStateSetAllTextures,
  sceGxmPrecomputedFragmentStateSetAllUniformBuffers,
  sceGxmPrecomputedFragmentStateSetDefaultUniformBuffer,
  sceGxmPrecomputedFragmentStateSetTexture,
  sceGxmPrecomputedFragmentStateSetUniformBuffer,
  sceGxmPrecomputedVertexStateGetDefaultUniformBuffer,
  sceGxmPrecomputedVertexStateInit,
  sceGxmPrecomputedVertexStateSetAllTextures,
  sceGxmPrecomputedVertexStateSetAllUniformBuffers,
  sceGxmPrecomputedVertexStateSetDefaultUniformBuffer,
  sceGxmPrecomputedVertexStateSetTexture,
  sceGxmPrecomputedVertexStateSetUniformBuffer,
  sceGxmProgramCheck,
  sceGxmProgramFindParameterByName,
  sceGxmProgramFindParameterBySemantic,
  sceGxmProgramGetDefaultUniformBufferSize,
  sceGxmProgramGetFragmentProgramInputs,
  sceGxmProgramGetOutputRegisterFormat,
  sceGxmProgramGetParameter,
  sceGxmProgramGetParameterCount,
  sceGxmProgramGetSize,
  sceGxmProgramGetType,
  sceGxmProgramGetVertexProgramOutputs,
  sceGxmProgramIsDepthReplaceUsed,
  sceGxmProgramIsDiscardUsed,
  sceGxmProgramIsEquivalent,
  sceGxmProgramIsFragColorUsed,
  sceGxmProgramIsNativeColorUsed,
  sceGxmProgramIsSpriteCoordUsed,
  sceGxmProgramParameterGetArraySize,
  sceGxmProgramParameterGetCategory,
  sceGxmProgramParameterGetComponentCount,
  sceGxmProgramParameterGetContainerIndex,
  sceGxmProgramParameterGetIndex,
  sceGxmProgramParameterGetName,
  sceGxmProgramParameterGetResourceIndex,
  sceGxmProgramParameterGetSemantic,
  sceGxmProgramParameterGetSemanticIndex,
  sceGxmProgramParameterGetType,
  sceGxmProgramParameterIsRegFormat,
  sceGxmProgramParameterIsSamplerCube,
  sceGxmPushUserMarker,
  sceGxmRemoveRazorGpuCaptureBuffer,
  sceGxmRenderTargetGetDriverMemBlock,
  sceGxmRenderTargetGetHostMem,
  sceGxmReserveFragmentDefaultUniformBuffer,
  sceGxmReserveVertexDefaultUniformBuffer,
  sceGxmSetAuxiliarySurface,
  sceGxmSetBackDepthBias,
  sceGxmSetBackDepthFunc,
  sceGxmSetBackDepthWriteEnable,
  sceGxmSetBackFragmentProgramEnable,
  sceGxmSetBackLineFillLastPixelEnable,
  sceGxmSetBackPointLineWidth,
  sceGxmSetBackPolygonMode,
  sceGxmSetBackStencilFunc,
  sceGxmSetBackStencilRef,
  sceGxmSetBackVisibilityTestEnable,
  sceGxmSetBackVisibilityTestIndex,
  sceGxmSetBackVisibilityTestOp,
  sceGxmSetCullMode,
  sceGxmSetDefaultRegionClipAndViewport,
  sceGxmSetDeferredContextFragmentBuffer,
  sceGxmSetDeferredContextVdmBuffer,
  sceGxmSetDeferredContextVertexBuffer,
  sceGxmSetFragmentDefaultUniformBuffer,
  sceGxmSetFragmentProgram,
  sceGxmSetFragmentTexture,
  sceGxmSetFragmentUniformBuffer,
  sceGxmSetFrontDepthBias,
  sceGxmSetFrontDepthFunc,
  sceGxmSetFrontDepthWriteEnable,
  sceGxmSetFrontFragmentProgramEnable,
  sceGxmSetFrontLineFillLastPixelEnable,
  sceGxmSetFrontPointLineWidth,
  sceGxmSetFrontPolygonMode,
  sceGxmSetFrontStencilFunc,
  sceGxmSetFrontStencilRef,
  sceGxmSetFrontVisibilityTestEnable,
  sceGxmSetFrontVisibilityTestIndex,
  sceGxmSetFrontVisibilityTestOp,
  sceGxmSetPrecomputedFragmentState,
  sceGxmSetPrecomputedVertexState,
  sceGxmSetRegionClip,
  sceGxmSetTwoSidedEnable,
  sceGxmSetUniformDataF,
  sceGxmSetUserMarker,
  sceGxmSetValidationEnable,
  sceGxmSetVertexDefaultUniformBuffer,
  sceGxmSetVertexProgram,
  sceGxmSetVertexStream,
  sceGxmSetVertexTexture,
  sceGxmSetVertexUniformBuffer,
  sceGxmSetViewport,
  sceGxmSetViewportEnable,
  sceGxmSetVisibilityBuffer,
  sceGxmSetWBufferEnable,
  sceGxmSetWClampEnable,
  sceGxmSetWClampValue,
  sceGxmSetWarningEnabled,
  sceGxmSetYuvProfile,
  sceGxmShaderPatcherAddRefFragmentProgram,
  sceGxmShaderPatcherAddRefVertexProgram,
  sceGxmShaderPatcherCreate,
  sceGxmShaderPatcherCreateFragmentProgram,
  sceGxmShaderPatcherCreateMaskUpdateFragmentProgram,
  sceGxmShaderPatcherCreateVertexProgram,
  sceGxmShaderPatcherDestroy,
  sceGxmShaderPatcherForceUnregisterProgram,
  sceGxmShaderPatcherGetBufferMemAllocated,
  sceGxmShaderPatcherGetFragmentProgramRefCount,
  sceGxmShaderPatcherGetFragmentUsseMemAllocated,
  sceGxmShaderPatcherGetHostMemAllocated,
  sceGxmShaderPatcherGetProgramFromId,
  sceGxmShaderPatcherGetUserData,
  sceGxmShaderPatcherGetVertexProgramRefCount,
  sceGxmShaderPatcherGetVertexUsseMemAllocated,
  sceGxmShaderPatcherRegisterProgram,
  sceGxmShaderPatcherReleaseFragmentProgram,
  sceGxmShaderPatcherReleaseVertexProgram,
  sceGxmShaderPatcherSetAuxiliarySurface,
  sceGxmShaderPatcherSetUserData,
  sceGxmShaderPatcherUnregisterProgram,
  sceGxmSyncObjectCreate,
  sceGxmSyncObjectDestroy,
  sceGxmTerminate,
  sceGxmTextureGetData,
  sceGxmTextureGetFormat,
  sceGxmTextureGetGammaMode,
  sceGxmTextureGetHeight,
  sceGxmTextureGetLodBias,
  sceGxmTextureGetLodMin,
  sceGxmTextureGetMagFilter,
  sceGxmTextureGetMinFilter,
  sceGxmTextureGetMipFilter,
  sceGxmTextureGetMipmapCount,
  sceGxmTextureGetMipmapCountUnsafe,
  sceGxmTextureGetNormalizeMode,
  sceGxmTextureGetPalette,
  sceGxmTextureGetStride,
  sceGxmTextureGetType,
  sceGxmTextureGetUAddrMode,
  sceGxmTextureGetUAddrModeSafe,
  sceGxmTextureGetVAddrMode,
  sceGxmTextureGetVAddrModeSafe,
  sceGxmTextureGetWidth,
  sceGxmTextureInitCube,
  sceGxmTextureInitCubeArbitrary,
  sceGxmTextureInitLinear,
  sceGxmTextureInitLinearStrided,
  sceGxmTextureInitSwizzled,
  sceGxmTextureInitSwizzledArbitrary,
  sceGxmTextureInitTiled,
  sceGxmTextureSetData,
  sceGxmTextureSetFormat,
  sceGxmTextureSetGammaMode,
  sceGxmTextureSetHeight,
  sceGxmTextureSetLodBias,
  sceGxmTextureSetLodMin,
  sceGxmTextureSetMagFilter,
  sceGxmTextureSetMinFilter,
  sceGxmTextureSetMipFilter,
  sceGxmTextureSetMipmapCount,
  sceGxmTextureSetNormalizeMode,
  sceGxmTextureSetPalette,
  sceGxmTextureSetStride,
  sceGxmTextureSetUAddrMode,
  sceGxmTextureSetUAddrModeSafe,
  sceGxmTextureSetVAddrMode,
  sceGxmTextureSetVAddrModeSafe,
  sceGxmTextureSetWidth,
  sceGxmTextureValidate,
  sceGxmTransferCopy,
  sceGxmTransferDownscale,
  sceGxmTransferFill,
  sceGxmTransferFinish,
  sceGxmUnmapFragmentUsseMemory,
  sceGxmUnmapMemory,
  sceGxmUnmapVertexUsseMemory,
  sceGxmVertexFence,
  sceGxmVertexProgramGetProgram,
  sceGxmWaitEvent,
  Max,
};